<?php

function bench_preprocess_block(&$variables) {
    $block = $variables['block'];
    // print "<pre>";
    // print_r($block);
    // print "</pre>";
    if ($block->module == 'views' && $block->delta == 'projects-block') {
      $variables['title_attributes_array']['class'][] = 'project-section';
    }
    if ($block->module == 'views' && $block->delta == 'about_me-block') {
      $variables['title_attributes_array']['class'][] = 'about-section';
    }
}

function bench_preprocess_views_view(&$variables) {

  if ($variables['view']->name == 'projects' && $variables['view']->current_display == 'block') {

    $variables['classes_array'][4] = 0 ;
  }
}
